config/routes.rb
XfireOauthConsumer::Application.routes.draw do
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "welcome/index"

  devise_for :users

  root :to => "welcome#index"

end

app/models/consumer_token.rb
require 'oauth/models/consumers/token'
class ConsumerToken < ActiveRecord::Base
  include Oauth::Models::Consumers::Token

  # You can safely remove this callback if you don't allow login from any of your services
  before_create :create_user

  # Modify this with class_name etc to match your application
  belongs_to :user

end

app/models/test_token.rb
class TestToken < ConsumerToken
  TEST_SETTINGS={
    :site => "http://dev.xfire.com:3000",
    :request_token_path => "/oauth/request_token",
    :access_token_path => "/oauth/access_token",
    :authorize_path => "/oauth/authorize"
  }
 
  def self.consumer(options={})
    @consumer ||= OAuth::Consumer.new(credentials[:key], credentials[:secret], TEST_SETTINGS.merge(options))
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_one  :test, :class_name=>"TestToken", :dependent=>:destroy
end


#Consumer Key: L808Pkq2isydyYy391YB6wkVbWpGWYgeg8db656o
#Consumer Secret: TttXikfk9wDV1ubuxQQzJbAo4Me0rt9hc5UnhCwK

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oauth_consumers_controller.rb
require 'oauth/controllers/consumer_controller'
class OauthConsumersController < ApplicationController
  include Oauth::Controllers::ConsumerController
  # Replace this with the equivalent for your authentication framework
  # Eg. for devise
  #
  before_filter :authenticate_user!, :only=>:index

  def index
    @consumer_tokens=ConsumerToken.all :conditions=>{:user_id=>current_user.id}
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
  end

  def callback
  	super
  end

  def client
    super
  end


  protected

  # Change this to decide where you want to redirect user to after callback is finished.
  # params[:id] holds the service name so you could use this to redirect to various parts
  # of your application depending on what service you're connecting to.
  def go_back
    redirect_to root_url
  end

  # The plugin requires logged_in? to return true or false if the user is logged in. Uncomment and
  # call your auth frameworks equivalent below if different. eg. for devise:
  #
  def logged_in?
    user_signed_in?
  end

  # The plugin requires current_user to return the current logged in user. Uncomment and
  # call your auth frameworks equivalent below if different.
  # def current_user
  #   current_person
  # end

  # The plugin requires a way to log a user in. Call your auth frameworks equivalent below
  # if different. eg. for devise:
  #
  def current_user=(user)
    sign_in(user)
  end

  # Override this to deny the user or redirect to a login screen depending on your framework and app
  # if different. eg. for devise:
  #
  #def deny_access!
  #  raise Acl9::AccessDenied
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    # cf http://oauth.rubyforge.org/rdoc/classes/OAuth/AccessToken.html
    @consumer_tokens=TestToken.all :conditions=>{:user_id=>current_user.id}
    if @consumer_tokens.length > 0
      @token = @consumer_tokens.first.client
      logger.info "private data: "+@token.get("/data/index").body
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XfireOauthConsumer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/oauth_consumers/index.html.erb
<h1>Services</h1>

<% if @consumer_tokens.empty? %>
  <p>
    You are currently not connected to any external services.
  </p>
<% else %>
  <p>
    You are connected to the following services:
  </p>
  <ul>
    <% @consumer_tokens.each do |token| %>
      <li>
        <%= link_to token.class.service_name.to_s.humanize, oauth_consumer_path(token.class.service_name) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% unless @services.empty? %>
<h3>You can connect to the following services:</h3>
<ul>
  <% @services.each do |service| %>
    <li>
      <%= link_to service.to_s.humanize, oauth_consumer_path(service) %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/oauth_consumers/show.html.erb
<h1>You are already Connected to <%=params[:id].humanize%></h1>
<% form_tag oauth_consumer_path(params[:id]),:method=>:delete do %>
  <%=submit_tag "Disconnect" %>
  or
  <%=submit_tag "Reconnect" %>
  if you experienced a problem.
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>